### ISSUE TITLE
Nothing auto plays in the direct messages page

### ISSUE THREAD

**Issue by Kanin** [GriefMoDz/autoplayGifAvatars#1]
Explains itself, nothing auto plays while you're viewing your direct messages. It does in chat however not in the list of people/groups.

**Comment by GriefMoDz** [comment]
Thanks for the report! This bug has been addressed in 41e2d75a4be169107886e1cd94a2b6c40c516fe4.

**Comment by Kanin** [comment]
Still doesn't seem to be working for me? @GriefMoDz
