### ISSUE TITLE
Crash Looping Powercord New Update

### ISSUE THREAD

**Issue by Twizzer** [GriefMoDz/autoplayGifAvatars#2]
Canary recently pushed an update that broke powercord, Powercord updated and now this plugin causes repeated crash looping at start of discord.

**Comment by PikaDude** [comment]
I've located that this particular line appears to be causing the crash.

https://github.com/GriefMoDz/autoplay-gifs/blob/3e8954b1378419be3fa4ceab95745f9927d658d8/index.js#L152

For a temporary fix, you can put a return statement at the beginning of the `patchGuildList` function.
