### ISSUE TITLE
User Message PFPs no longer animate

### ISSUE THREAD

**Issue by PikaDude** [GriefMoDz/autoplayGifAvatars#3]
Discord recently changed something, and now the message header injection no longer works. So when people send messages, their pfps no longer automatically animate.

**Comment by ghost** [comment]
I am also having this issue.

**Comment by xCancazedd** [comment]
<img width="428" alt="nMc3cqynhB" src="https://user-images.githubusercontent.com/81846939/115414469-adb1d080-a1bb-11eb-9e29-d20e2c8bbb64.png">

**Comment by supermxn** [comment]
Still having the same issue, message and member list does not auto play
